version: '3.9'
services:
  dofusapi:
    image: dofus_api_dev
    build:
      dockerfile: ./docker/dev/api.Dockerfile
    working_dir: /var/www/api
    environment:
      DEBUG: 1
      DATABASE_HOST: postgres
      DATABASE_NAME: dofusapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: "1234567890"
    volumes:
      - .:/var/www/api
    ports:
      - 8181:80
    networks:
      - dofus_network
networks:
  dofus_network:
    name: dofus_network
